spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: SA
    password: