spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: andersen0505!!
    url: jdbc:mariadb://localhost:3306/db_hibricks?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf8
    username: hibricks
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 10000
      connection-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 580000
  jpa:
    #open-in-view: false #https://kihoonkim.github.io/2017/01/27/JPA%28Java%20ORM%29/1.%20JPA-%ED%99%98%EA%B2%BD%20%EC%84%A4%EC%A0%95/
    generate-ddl: true
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        ##schema_update:
        ##unique_constraint_strategy: RECREATE_QUIETLY #https://discourse.hibernate.org/t/hbm2ddl-auto-update-recreating-existing-indexes-after-drop/3991
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: update
        show_sql: true
        format_sql: true