## GROUP
---
spring:
  profiles:
    group:
      local: local
---
spring:
  profiles:
    group:
      prod: prod
---
spring:
  profiles:
    group:
      mac: mac
## common (localhost, development, production)
---
spring:
  profiles:
    include:
